spring:
  application:
    name: spring-ai-chat-ollama
  profiles:
    active: ollama
  datasource:
    url: jdbc:mysql://localhost:3306/wxbot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: glm4:9b
        options:
          temperature: 0.7
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:schema-@@platform@@.sql
            platform: mysql

server:
  port: 8081

